apiVersion: v1
kind: Pod
metadata:
  name:  ngnixhttpd-pod
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
        - containerPort: 80
  containers:
    - name: httpd-pod
      image: httpd
      ports:
        - containerPort: 80         
