apiVersion: batch/v1
kind: CronJob
metadata: 
  name: cronjob
spec:
  schedule: "*/2" * * * *" 
  jobTemplate:
    metadata:
      name: tem-job
    spec:
      backoffLimit: 3
      template:
        metadata:
          name: containerjob
        spec:
          restartPolicy: OnFailure  
          containers:
            - name: alpine
              image: alpine
              command:
                - sleep
                - 1d


