apiVersion: batch/v1
kind: CronJob
metadata: 
  name: cronjob
spec:
  backoffLimit: 3
  jobTemplate:
    metadata:
      name: tem-job
    spec:
      template:
        metadata:
          name: containerjob
        spec:
          restartPolicy: OnFailure  
          containers:
            - name: alpine
              image: alpine
              command:
                - sleep
                - 5fm

