apiVersion: v1
kind: Pod
metadata:
  name: exec 
spec:
  restartPolicy:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
 
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d
     
     